# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_token_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='uid',
            field=models.CharField(default='123', max_length=40),
            preserve_default=False,
        ),
    ]
