# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0007_list_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='shared_with',
            field=models.ManyToManyField(related_name='user_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
